name: CI

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  test:
    if: "!contains(toJson(github.event.commits), '[skip ci]')"
    strategy:
      matrix:
        node-version: [12, 14, 16]
        ts-version: [4.0.x, 4.1.x, 4.2.x, 4.3.x, 4.4.x, 4.5.x, 4.6.x]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }} & Typescript ${{ matrix.ts-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          yarn install
          yarn add typescript@${{ matrix.ts-version }} --dev
      - run: yarn test
      - name: Coverage
        uses: codecov/codecov-action@v1
        if: matrix.node-version == '12' && matrix.ts-version == '4.2.x' && github.ref == 'refs/heads/master'
